--- 
title: "R for Excel Users"
author: "Julie Lowndes & Allison Horst"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a workshop for RStudio::conf(2020) in San Francisco, California"
---

# Welcome {#welcome}

Hello! This is a workshop taught by Julie Stewart Lowndes and Allison Horst at the RStudio Conference: January 27-28 in San Francisco, California. 

We are environmental scientists who use and teach R in our daily work. We both work at the University of California Santa Barbara: Julie is based at the National Center for Ecological Analysis and Synthesis as part of the Ocean Health Index team and leads Openscapes, and Allison is based at the Bren School of Environmental Science and Management as a lecturer of data science & statistics — and is also an Artist in Residence at RStudio.

<!---
We are on Twitter:

Excel is a widely used and powerful tool for working with data. As automation, reproducibility, collaboration, and frequent reporting become increasingly expected in data analysis, a good option for Excel users is to extend their workflows with R. Integrating R into data analysis with Excel can bridge the technical gap between collaborators using either software. R enables use of existing tools built for specific tasks and overcomes some limitations that arise when working with large datasets or repeated analyses. This course is for Excel users who want to add or integrate R and RStudio into their existing data analysis toolkit. Participants will get hands-on experience working with data across R, Excel, and Google Sheets, focusing on: data import and export, basic wrangling, visualization, and reporting with RMarkdown. Throughout, we will emphasize conventions and best practices for working reproducibly and collaboratively with data, including naming conventions, documentation, organization, all while “keeping the raw data raw”. Whether you are working in Excel and want to get started in R, already working in R and want tools for working more seamlessly with collaborators who use Excel, or whether you are new to data analysis entirely, this is the course for you! 

If you answer yes to these questions, this course is for you!

- Are you an Excel user who wants to expand your data analysis toolset with R?
- Do you want to bridge analyses between Excel and R, whether working independently or to more easily collaborate with others who use Excel or R? 
- Are you new to data analysis, and looking for a good place to get started?

--->

 <!--- This is going to be fun, because learning R (and friends) is empowering! This training book is written (and always improving) so you can use it as self-paced learning, or it can be used to teach an in-person workshop where the instructor live-codes. Either way, you should do everything hands-on on your own computer as you learn. 

Before you begin, be sure you are all set up: see the prerequisites in Chapter \@ref(overview). --->

## Agenda


|Time       |      Day 1|      Day 2|
|:----------|----------:|----------:|
|9-10:30    |  [Motivation](#overview), [R & RStudio, RMarkdown](#rstudio) (JL) |  [Tidying data ](#tidying) (AH) |
|break      |  | |
|11-12:30   | [Intro to GitHub](#github) (JL) | [`dplyr` & VLOOKUPs](#dplyr-vlookups) (AH) |
|lunch      |  ||
|13:30-15:00 | [`ggplot2` & Charts](#ggplot2) (AH) | [Collaborating & getting help](#collaboration) (JL) |
|break      |  | |
|15:30-17:00 | [`dplyr` & Pivot Tables](#dplyr-pivot-tables) (JL) | [Synthesis](#synthesis) (AH) |


## Prerequisites

Before the training, please make sure you have done the following: 

1. Download and install **up-to-date versions** of:
    - R: https://cloud.r-project.org
    - RStudio: http://www.rstudio.com/download 
1. Install the Tidyverse TODO--no longer?
1. Create a GitHub account ([username advice](https://happygitwithr.com/github-acct.html)): 
    - https://github.com
    - remember your username, email and password (we will need them for the workshop!)
1. Download and install **Git** TODO discuss    
1. Download the [r-for-excel-data folder](https://drive.google.com/drive/folders/1RywSUw8hxETlROdIhLIntxPsZq0tKSdS?usp=sharing) (we will move it somewhere together)
    
<!---
Do this beforehand (20 minutes)

    Download & install free software: R, RStudio, tidyverse. Do this following Allison’s step-by-step instructions (from her ESM 206 course)

    Create a GitHub username at github.com. We recommend shorter names that identify you, and using your work email address (where you primarily do analyses)
https://docs.google.com/document/d/1Imcx8ZropMF5tmLF6As02OJam-r1pNexu5pULczCwMA/edit?ts=5d8ce185 --->   

1. Get comfortable: if you're not in a physical workshop, be set up with two screens if possible. You will be following along in RStudio on your own computer while also watching a virtual training or following this tutorial on your own.

## Data citations

We use the following data from the Santa Barbara Coastal Term Ecological Research and National  Oceanic and Atmospheric Administration in this workshop: 

- **fish.csv**
  - Description: Reef fish abundance, SB coast
  - Link: https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=17&revision=newest
  - Citation: Reed D. 2018. SBC LTER: Reef: Kelp Forest Community Dynamics: Fish abundance. Environmental Data Initiative. [doi](https://doi.org/10.6073/pasta/dbd1d5f0b225d903371ce89b09ee7379).
- **inverts.xlsx**
  - Description: Invertebrate counts, SB coast
  - Link: https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=19&revision=newest
  - Citation: Reed D. 2018. SBC LTER: Reef: Kelp Forest Community Dynamics: Invertebrate and algal density. Environmental Data Initiative. [doi](https://doi.org/10.6073/pasta/748ee568669ca2b740e9b8f5f8a085d8). 
- **kelp.xlsx**
  - Description: Giant kelp abundance and size, SB coast
  - Link: https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=18&revision=newest                        
  - Citation: Reed D. 2018. SBC LTER: Reef: Kelp Forest Community Dynamics: Abundance and size of Giant Kelp (Macrocystis Pyrifera), ongoing since 2000. Environmental Data Initiative. [doi](https://doi.org/10.6073/pasta/dea56e02127161194626f97c8b6118e8). 
- **lobsters.xlsx and lobsters2.xlsx**
  - Description: Lobster size, abundance and fishing pressure (SB coast)
  - Link: https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=77&revision=newest
  - Citation: Reed D. 2019. SBC LTER: Reef: Abundance, size and fishing effort for California Spiny Lobster (Panulirus interruptus), ongoing since 2012. Environmental Data Initiative. [doi](https://doi.org/10.6073/pasta/a593a675d644fdefb736750b291579a0). 
- **noaa_fisheries.csv**
  - Description: NOAA Commercial Fisheries Landing data (1950 - 2017)
  - Link: https://www.st.nmfs.noaa.gov/commercial-fisheries/commercial-landings/
  - Source: Fisheries Statistics Division of the NOAA Fisheries
- **substrate.xlsx **
  - Description: Algal cover, invertebrates and substrates near Santa Cruz Island
  - Link: https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=38&revision=newest
  - Citation: Schmitt R. J., S. J. Holbrook. 2012. SBC LTER: Santa Cruz Island: Cover of Algae, Invertebrates and Benthic Substrate. Environmental Data Initiative. [doi](https://doi.org/10.6073/pasta/9ce22c5b70d3e6ef8f0445e6cf782f87). 
- **ca_np.csv and ci_np.xlsx**
  - Description: US National Parks visitation data (1904 - 2016)
  - Link: https://data.world/inform8n/us-national-parks-visitation-1904-2016-with-boundaries
  - Source: Data originally accessed from the US Department of the Interior National Park Service’s Integrated Resource Management Applications data portal (https://irma.nps.gov/)
